application: go-tour-uz
version: 1
runtime: go
api_version: go1

default_expiration: "7d"

handlers:

# Keep these static file handlers in sync with gotour/local.go.
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
- url: /content/img
  static_dir: content/img
- url: /static
  static_dir: static
  application_readable: true

- url: /(.*|list|lesson/.*|compile|fmt|script\.js)
  script: _go_app

nobuild_files: (solutions|content)/.*
